// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_lP5aLfhSqTAR6kBFudf7pE8laaAqMU',
    appId: '1:446584745622:web:266d738118df81db5cdcb7',
    messagingSenderId: '446584745622',
    projectId: 'earthcare-51d1a',
    authDomain: 'earthcare-51d1a.firebaseapp.com',
    storageBucket: 'earthcare-51d1a.firebasestorage.app',
    measurementId: 'G-6W2XEJVTZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS0VNwsZbsztf2fGZBfcHMFvQJbzAbIkw',
    appId: '1:446584745622:android:dafe8e69c90795e05cdcb7',
    messagingSenderId: '446584745622',
    projectId: 'earthcare-51d1a',
    storageBucket: 'earthcare-51d1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJy1m4ExDgN9VP8Cm9AJV4-VcbZ2t9GaQ',
    appId: '1:446584745622:ios:cb8e9837c60717125cdcb7',
    messagingSenderId: '446584745622',
    projectId: 'earthcare-51d1a',
    storageBucket: 'earthcare-51d1a.firebasestorage.app',
    iosBundleId: 'com.example.earthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJy1m4ExDgN9VP8Cm9AJV4-VcbZ2t9GaQ',
    appId: '1:446584745622:ios:cb8e9837c60717125cdcb7',
    messagingSenderId: '446584745622',
    projectId: 'earthcare-51d1a',
    storageBucket: 'earthcare-51d1a.firebasestorage.app',
    iosBundleId: 'com.example.earthCare',
  );
}
